# Generated by Django 3.2.16 on 2023-11-12 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='quantity',
            new_name='amount',
        ),
    ]
